services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: techcoder01
      POSTGRES_PASSWORD: F8XMymjiT4IjPD2oXvyNf8UOthRN0R0M
      POSTGRES_DB: goauth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - go-network

networks:
  go-network:
    driver: bridge

volumes:
  postgres_data:
